image: registry.gitlab.com/panw-gse/as/panos_skillet_tools:latest

before_script:
  - python -V  # Print out python version for debugging

test:
  script:
    - ansible-playbook -i inventory.yml manage_panos_software.yml --syntax-check
    - ansible-lint manage_panos_software.yml -v

